# Generated by Django 5.1.7 on 2025-03-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofile',
            name='income_sources',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='IncomeSource',
        ),
        migrations.DeleteModel(
            name='InvestorProfile',
        ),
    ]
