# Generated by Django 5.1.7 on 2025-03-31 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
