# Generated by Django 5.1.7 on 2025-04-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_delete_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
