# Generated by Django 5.1.7 on 2025-04-10 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('founder_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('business_location', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(choices=[('Technology', 'Technology'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Other', 'Other')], max_length=20)),
                ('funding_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('equity_offered', models.FloatField(default=0.0)),
                ('expected_roi', models.FloatField(default=0.0)),
                ('revenue_model', models.CharField(blank=True, max_length=255)),
                ('projected_revenue', models.TextField(blank=True)),
                ('business_plan', models.FileField(blank=True, null=True, upload_to='business_plans/')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='registration_docs/')),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='pitch_decks/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(default='000000', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('investment_preferences', models.TextField(blank=True)),
                ('portfolio_size', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('income_sources', models.CharField(blank=True, max_length=50)),
                ('employment_status', models.CharField(blank=True, max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('beneficial_owner', models.BooleanField(default=False)),
                ('investor_type', models.CharField(default='Individual', max_length=20)),
                ('investment_size', models.CharField(default='Small', max_length=10)),
                ('sector', models.CharField(choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Real Estate', 'Real Estate'), ('Education', 'Education'), ('Energy', 'Energy'), ('Other', 'Other')], default='Other', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
