# Generated by Django 5.1.7 on 2025-04-03 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Unnamed Project', max_length=255)),
                ('description', models.TextField(default='No description available.')),
                ('funding_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sector', models.CharField(default='General', max_length=255)),
                ('expected_return', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('projected_revenue', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_preferences', models.TextField()),
                ('portfolio_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
