# Generated by Django 5.1.7 on 2025-04-11 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorprofile',
            old_name='investment_preferences',
            new_name='industries_of_interest',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='beneficial_owner',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='income_sources',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='investor_type',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='portfolio_size',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='sector',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='amount_raised',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending Review'), ('funded', 'Funded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='investment_duration',
            field=models.CharField(choices=[('short', 'Short Term (≤ 1 year)'), ('mid', 'Medium Term (1-3 years)'), ('long', 'Long Term (3+ years)')], default='mid', max_length=10),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='level',
            field=models.CharField(default='Newbie', max_length=100),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='preferred_investment_type',
            field=models.CharField(choices=[('equity', 'Equity'), ('loan', 'Loan-Based'), ('revenue', 'Revenue Sharing'), ('donation', 'Donation-Based')], default='equity', max_length=20),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='profile_image',
            field=models.ImageField(default='default-avatar.png', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='roi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_plan',
            field=models.FileField(blank=True, null=True, upload_to='media/business_plans/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='founder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='funding_required',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='media/pitch_decks/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='project_image',
            field=models.ImageField(default='default.jpg', upload_to='media/project_images/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='projected_revenue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='media/registration_documents/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='revenue_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='sector',
            field=models.CharField(choices=[('Tech', 'Technology'), ('Edu', 'Education'), ('Fin', 'Finance'), ('Med', 'Healthcare'), ('Agr', 'Agriculture'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired')], default='unemployed', max_length=20),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='investment_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.investorprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
