# Generated by Django 5.1.7 on 2025-04-05 03:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='expected_return',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_location',
            field=models.CharField(default='Unspecified', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_plan',
            field=models.FileField(default='N/A', upload_to='business_plans/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='equity_offered',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='expected_roi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='founder_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='pitch_deck',
            field=models.FileField(default='N/A', upload_to='pitch_decks/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='project_image',
            field=models.ImageField(default='default.jpg', upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='registration_document',
            field=models.FileField(default='N/A', upload_to='registration_documents/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='registration_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='revenue_model',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='beneficial_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='employment_status',
            field=models.CharField(default='Unemployed', max_length=20),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='first_name',
            field=models.CharField(default='John', max_length=30),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='id_number',
            field=models.CharField(default='000000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='income_sources',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='investment_size',
            field=models.CharField(default='Small', max_length=10),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='investor_type',
            field=models.CharField(default='Individual', max_length=20),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='last_name',
            field=models.CharField(default='Doe', max_length=30),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='middle_name',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='sector',
            field=models.CharField(choices=[('Technology', 'Technology')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='projected_revenue',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='sector',
            field=models.CharField(choices=[('Technology', 'Technology')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='investment_preferences',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='portfolio_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
