# Generated by Django 5.1.7 on 2025-04-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='sector',
            field=models.CharField(choices=[('Tec', 'Tech')], default='Other', max_length=20),
        ),
    ]
