# Generated by Django 5.1.7 on 2025-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_businessprofile_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_plan',
            field=models.FileField(default='N/A', upload_to='media/business_plans/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='pitch_deck',
            field=models.FileField(default='N/A', upload_to='media/registration_documents/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='project_image',
            field=models.ImageField(default='default.jpg', upload_to='media/project_images/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='registration_document',
            field=models.FileField(default='N/A', upload_to='media/registration_documents/'),
        ),
    ]
