# Generated by Django 5.1.7 on 2025-04-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_businessprofile_business_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business_plan',
            field=models.FileField(blank=True, null=True, upload_to='business_plans/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='pitch_decks/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='registration_docs/'),
        ),
    ]
