# Generated by Django 5.1.7 on 2025-04-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_businessprofile_business_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='sector',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='sector',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Real Estate', 'Real Estate'), ('Education', 'Education'), ('Energy', 'Energy'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
