# Generated by Django 5.1.7 on 2025-03-31 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sector', models.CharField(choices=[('Technology', 'Technology'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=100)),
                ('funding_required', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('founders', models.TextField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('revenue_model', models.TextField(blank=True, null=True)),
                ('expected_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('projected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('business_plan', models.FileField(blank=True, null=True, upload_to='business_plans/')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
