# Generated by Django 5.1.7 on 2025-04-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_business', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
